[IMPORTANT]
====
*this project has been moved to codeberg*
*link*: https://codeberg.org/t0mri/cya[https://codeberg.org/t0mri/cya]
====

= cya
:author: t0mri
:revnumber: 0.0.1
:toc:

pronounced as `see ya`. 'c' for c and 'ya' for youtube

== introduction
*{doctitle}* is a program written in `c` to search (unlimited) and watch
youtube videos from tty/cli! it's intended for educational purposes, to explore
how youtube search results can be programmatically accessed and manipulated

video::https://github.com/t0mri/cya/assets/123792488/39e7e710-4c3d-4f3b-8912-cc2ae67aa334[]

== installation

you can download the binary form https://github.com/t0mri/cya/releases[releases]
page or https://github.com/t0mri/cya?tab=readme-ov-file#building[compile] it
yourself, which *takes less than one seconod*

=== building

*1. get a local copy*
[source,bash]
----
git clone https://github.com/t0mri/cya && cd cya
----
*2. compile*
[source,bash]
----
gcc -o cya main.c libcya/cya.c -lcurl -lcjson -lmpv
----
that's it, now youre ready *make your first cya search with `./cya <your_query>`*

== caveat

- youd have to download about 1mb response, instead of 800kb one

[IMPORTANT]
====
please note that this project is intended for educational purposes only.
it is not intended to be used in a manner that violates youtube's terms of
service or google's policies.
====
